### PR TITLE
Serve menu data via GQL or API

### PR DESCRIPTION
**Pull request by tautvydasr**
Currently, the majority of the web pages in the OT infrastructure consume data from GraphQL or APIs but the code challenge serves static menu data and it's impossible to check the candidate's experience working with external data sources. 

This PR adds the simple GraphQL and API instances to the code test so we will be able to see:
- How the candidate works with external data sources
- How the candidate handles errors
- How the candidate deals with a loading app state

The preferred way is to use GraphQL for fetching menu data but if the candidate has zero experience and is not comfortable working with it the API endpoint `/api/v1/menu` could be used as an alternative.

### CODE REVIEW

**Review by Savzzy — APPROVED** [review]

**Review by ZilvinasAbr — APPROVED** [review]

**Review by psaulenas — COMMENTED** [review]
Good job! Looks good and was working for me.
Could we also upgrade `html-webpack-plugin`? There is a warning that `html-webpack-plugin@3.2.0: 3.x is no longer supported`

**Comment by tautvydasr** [comment]
I have updated outdated packages. Take a look, please.

**Review by JustasBeresnevicius — APPROVED** [review]
GJ!

**Review by federicomaffei — APPROVED** [review]
Great work T

**Pull request merged**
